version: "2.4"

services:
  db:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password10
      POSTGRES_DB: userDB
    networks:
      - app_net
    volumes:
      - db-cache:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  dev:
    image: gradle:5.5.1-jdk11
    working_dir: /app
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: userDB
      DB_USER: postgres
      DB_PASSWORD: password10
    command: ./gradlew bootRun
    depends_on:
      - db
    networks:
      - app_net
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
networks:
  app_net:

volumes:
  db-cache:
  gradle-cache:
