version: "2.4"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: userDB
      MYSQL_ROOT_PASSWORD: 12345678
    restart: always
    ports:
      - "3305:3306"
    networks:
      - app_net
  dev:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_net
networks:
  app_net: