version: "2.4"

services:
  db:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password10
      POSTGRES_DB: userDB
    networks:
      - app_net
    volumes:
      - db-cache:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  dev:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: userDB
      DB_USER: postgres
      DB_PASSWORD: password10
    depends_on:
      - db
    networks:
      - app_net
networks:
  app_net:

volumes:
  db-cache: