server:
  port: 8080

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    web:
      exposure:
        include: prometheus
eureka:
  client:
    service-url:
      defaultZone: http://docker.for.mac.localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true
      